# Site settings
author: Liz A.
title: TerrANOVA
header-img: img/home-bg.png
email: alvarezlizc@gmail.com
copyright_name: Liz A.
description: > # this means to ignore newlines until "baseurl:"
  Exploring Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alvacat

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
